In [1]:
import pandas as pd

In [2]:
matches=pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City

In [4]:
matches.shape

(2052, 27)

In [43]:
matches[matches['team']=='Liverpool'].sort_values('date')

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4.0,3.0,Leeds United,...,0.0,2.0,2.0,2022,Liverpool,1,10,17,5,1
2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2.0,0.0,Chelsea,...,1.0,0.0,0.0,2022,Liverpool,0,6,16,6,1
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3.0,1.0,Arsenal,...,0.0,0.0,0.0,2022,Liverpool,1,0,20,0,1
6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2.0,7.0,Aston Villa,...,1.0,0.0,0.0,2022,Liverpool,0,1,19,6,0
7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2.0,2.0,Everton,...,2.0,0.0,0.0,2022,Liverpool,0,8,12,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,2023-05-03,20:00,Premier League,Matchweek 28,Wed,Home,W,1.0,0.0,Fulham,...,0.0,1.0,1.0,2022,Liverpool,1,9,20,2,1
48,2023-05-06,17:30,Premier League,Matchweek 35,Sat,Home,W,1.0,0.0,Brentford,...,0.0,0.0,0.0,2022,Liverpool,1,3,17,5,1
49,2023-05-15,20:00,Premier League,Matchweek 36,Mon,Away,W,3.0,0.0,Leicester City,...,1.0,0.0,0.0,2022,Liverpool,0,11,20,0,1
50,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1.0,1.0,Aston Villa,...,0.0,0.0,0.0,2022,Liverpool,1,1,15,5,0
51,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,D,4.0,4.0,Southampton,...,0.0,0.0,0.0,2022,Liverpool,0,19,16,6,0

In [44]:
matches['round'].value_counts()

Matchweek 1     54
Matchweek 30    54
Matchweek 23    54
Matchweek 12    54
Matchweek 24    54
Matchweek 25    54
Matchweek 26    54
Matchweek 27    54
Matchweek 29    54
Matchweek 31    54
Matchweek 2     54
Matchweek 33    54
Matchweek 34    54
Matchweek 28    54
Matchweek 35    54
Matchweek 36    54
Matchweek 37    54
Matchweek 32    54
Matchweek 22    54
Matchweek 21    54
Matchweek 7     54
Matchweek 20    54
Matchweek 3     54
Matchweek 4     54
Matchweek 5     54
Matchweek 6     54
Matchweek 8     54
Matchweek 9     54
Matchweek 10    54
Matchweek 11    54
Matchweek 13    54
Matchweek 14    54
Matchweek 15    54
Matchweek 16    54
Matchweek 17    54
Matchweek 18    54
Matchweek 19    54
Matchweek 38    54
Name: round, dtype: int64

In [45]:
del matches['comp']
del matches['notes']

In [46]:
matches.dtypes

date            datetime64[ns]
time                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
venue_code                int8
opp_code                  int8
hour                     int32
day_code                 int64
target                   int32
dtype: object

In [47]:
matches['date']=pd.to_datetime(matches['date'])
matches.dtypes

date            datetime64[ns]
time                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
venue_code                int8
opp_code                  int8
hour                     int32
day_code                 int64
target                   int32
dtype: object

In [48]:
matches['venue_code']=matches['venue'].astype('category').cat.codes

In [49]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,2.2,...,1.0,1.0,1.0,2022,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,1.7,...,0.0,0.0,0.0,2022,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,2.1,...,1.0,0.0,0.0,2022,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,2.2,...,0.0,0.0,0.0,2022,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,3.3,...,0.0,0.0,0.0,2022,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,2021-05-08,15:00,Matchweek 35,Sat,Away,W,2.0,0.0,Sheffield Utd,2.0,...,1.0,0.0,0.0,2022,Crystal Palace,0,18,15,5,1
36,2021-05-11,20:15,Matchweek 32,Tue,Away,L,1.0,3.0,Southampton,1.5,...,1.0,0.0,1.0,2022,Crystal Palace,0,19,20,1,0
37,2021-05-16,12:00,Matchweek 36,Sun,Home,W,3.0,2.0,Aston Villa,1.9,...,2.0,0.0,0.0,2022,Crystal Palace,1,1,12,6,1
38,2021-05-19,19:00,Matchweek 37,Wed,Home,L,1.0,3.0,Arsenal,1.0,...,0.0,0.0,0.0,2022,Crystal Palace,1,0,19,2,0
39,2021-05-23,16:00,Matchweek 38,Sun,Away,L,0.0,2.0,Liverpool,0.6,...,1.0,0.0,0.0,2022,Crystal Palace,0,12,16,6,0

In [50]:
matches['opp_code']=matches['opponent'].astype('category').cat.codes

In [51]:
matches['hour']=matches['time'].str.replace(":.+", "", regex=True).astype('int')

In [52]:
matches['day_code']=matches['date'].dt.dayofweek

In [53]:
matches['target']=(matches['result']=='W').astype('int')

In [54]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,2.2,...,1.0,1.0,1.0,2022,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,1.7,...,0.0,0.0,0.0,2022,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,2.1,...,1.0,0.0,0.0,2022,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,2.2,...,0.0,0.0,0.0,2022,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,3.3,...,0.0,0.0,0.0,2022,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,2021-05-08,15:00,Matchweek 35,Sat,Away,W,2.0,0.0,Sheffield Utd,2.0,...,1.0,0.0,0.0,2022,Crystal Palace,0,18,15,5,1
36,2021-05-11,20:15,Matchweek 32,Tue,Away,L,1.0,3.0,Southampton,1.5,...,1.0,0.0,1.0,2022,Crystal Palace,0,19,20,1,0
37,2021-05-16,12:00,Matchweek 36,Sun,Home,W,3.0,2.0,Aston Villa,1.9,...,2.0,0.0,0.0,2022,Crystal Palace,1,1,12,6,1
38,2021-05-19,19:00,Matchweek 37,Wed,Home,L,1.0,3.0,Arsenal,1.0,...,0.0,0.0,0.0,2022,Crystal Palace,1,0,19,2,0
39,2021-05-23,16:00,Matchweek 38,Sun,Away,L,0.0,2.0,Liverpool,0.6,...,1.0,0.0,0.0,2022,Crystal Palace,0,12,16,6,0

In [55]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
rf=RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [57]:
train=matches[matches['date']<'2022-01-01']

In [58]:
test=matches[matches['date']>'2022-01-01']

In [59]:
predictors=['venue_code', "opp_code","hour", "day_code"]

In [60]:
rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [61]:
preds=rf.predict(test[predictors])

In [62]:
from sklearn.metrics import accuracy_score

In [86]:
error=accuracy_score(test['target'], preds)

In [87]:
error

0.5722996515679443

In [65]:
combined=pd.DataFrame(dict(actual=test['target'], prediction=preds))

In [88]:
pd.crosstab(index=combined['actual'], columns=combined['predicted'])

predicted    0    1
actual
0          549  145
1          276  169

In [89]:
from sklearn.metrics import precision_score

In [90]:
precision_score(test['target'], preds)

0.4404432132963989

In [69]:
grouped_matches=matches.groupby('team')

In [92]:
group=grouped_matches.get_group('Manchester City').sort_values('date')
group

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2020-09-21,20:15,Matchweek 2,Mon,Away,W,3.0,1.0,Wolves,1.9,...,2.0,1.0,1.0,2022,Manchester City,0,24,20,0,1
2,2020-09-27,16:30,Matchweek 3,Sun,Home,L,2.0,5.0,Leicester City,0.9,...,1.0,0.0,0.0,2022,Manchester City,1,11,16,6,0
4,2020-10-03,17:30,Matchweek 4,Sat,Away,D,1.0,1.0,Leeds United,1.2,...,1.0,0.0,0.0,2022,Manchester City,0,10,17,5,0
5,2020-10-17,17:30,Matchweek 5,Sat,Home,W,1.0,0.0,Arsenal,1.3,...,0.0,0.0,0.0,2022,Manchester City,1,0,17,5,1
7,2020-10-24,12:30,Matchweek 6,Sat,Away,D,1.0,1.0,West Ham,1.0,...,1.0,0.0,0.0,2022,Manchester City,0,23,12,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2023-05-06,15:00,Matchweek 35,Sat,Home,W,2.0,1.0,Leeds United,2.6,...,2.0,0.0,1.0,2022,Manchester City,1,10,15,5,1
54,2023-05-14,14:00,Matchweek 36,Sun,Away,W,3.0,0.0,Everton,0.8,...,2.0,0.0,0.0,2022,Manchester City,0,8,14,6,1
56,2023-05-21,16:00,Matchweek 37,Sun,Home,W,1.0,0.0,Chelsea,1.2,...,0.0,0.0,0.0,2022,Manchester City,1,6,16,6,1
57,2023-05-24,20:00,Matchweek 32,Wed,Away,D,1.0,1.0,Brighton,1.8,...,0.0,0.0,0.0,2022,Manchester City,0,4,20,2,0
58,2023-05-28,16:30,Matchweek 38,Sun,Away,L,0.0,1.0,Brentford,1.6,...,0.0,0.0,0.0,2022,Manchester City,0,3,16,6,0

In [93]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [94]:
cols=['gf','ga','sh', 'sot','dist','fk','pk','pkatt']

In [95]:
new_cols=[f"{c}_rolling" for c in cols]

In [97]:
rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,17:30,Matchweek 5,Sat,Home,W,1.0,0.0,Arsenal,1.3,...,5,1,2.000000,2.333333,17.333333,4.666667,19.700000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Matchweek 6,Sat,Away,D,1.0,1.0,West Ham,1.0,...,5,0,1.333333,2.000000,17.333333,3.666667,18.566667,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Matchweek 7,Sat,Away,W,1.0,0.0,Sheffield Utd,1.6,...,5,1,1.000000,0.666667,16.666667,4.333333,18.933333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Matchweek 8,Sun,Home,D,1.0,1.0,Liverpool,1.4,...,6,0,1.000000,0.333333,14.333333,6.666667,19.033333,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Matchweek 9,Sat,Away,L,0.0,2.0,Tottenham,1.4,...,5,0,1.000000,0.666667,12.000000,5.666667,20.000000,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2023-05-06,15:00,Matchweek 35,Sat,Home,W,2.0,1.0,Leeds United,2.6,...,5,1,3.000000,0.666667,13.666667,8.000000,15.433333,0.000000,0.333333,0.333333
54,2023-05-14,14:00,Matchweek 36,Sun,Away,W,3.0,0.0,Everton,0.8,...,6,1,2.333333,0.666667,14.666667,7.000000,16.366667,0.666667,0.333333,0.666667
56,2023-05-21,16:00,Matchweek 37,Sun,Home,W,1.0,0.0,Chelsea,1.2,...,6,1,2.666667,0.333333,14.000000,5.666667,18.100000,1.333333,0.000000,0.333333
57,2023-05-24,20:00,Matchweek 32,Wed,Away,D,1.0,1.0,Brighton,1.8,...,2,0,2.000000,0.333333,13.666667,4.000000,18.933333,1.333333,0.000000,0.333333
58,2023-05-28,16:30,Matchweek 38,Sun,Away,L,0.0,1.0,Brentford,1.6,...,6,0,1.666667,0.333333,12.333333,3.333333,17.333333,0.666667,0.000000,0.000000

In [96]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [75]:
matches_rolling=matches.groupby('team').apply(lambda x: rolling_averages(x, cols, new_cols))

In [76]:
matches_rolling

                                 date   time         round  day venue result  \
team
Arsenal                 6  2020-10-04  14:00   Matchweek 4  Sun  Home      W
                        7  2020-10-17  17:30   Matchweek 5  Sat  Away      L
                        9  2020-10-25  19:15   Matchweek 6  Sun  Home      L
                        11 2020-11-01  16:30   Matchweek 7  Sun  Away      W
                        13 2020-11-08  19:15   Matchweek 8  Sun  Home      L
...                               ...    ...           ...  ...   ...    ...
Wolverhampton Wanderers 39 2023-04-29  15:00  Matchweek 34  Sat  Away      L
                        40 2023-05-06  15:00  Matchweek 35  Sat  Home      W
                        41 2023-05-13  15:00  Matchweek 36  Sat  Away      L
                        42 2023-05-20  15:00  Matchweek 37  Sat  Home      D
                        43 2023-05-28  16:30  Matchweek 38  Sun  Away      L

                             gf   ga         opponent   xg  ...  day_code  \
team                                                        ...
Arsenal                 6   2.0  1.0    Sheffield Utd  0.6  ...         6
                        7   0.0  1.0  Manchester City  0.9  ...         5
                        9   0.0  1.0   Leicester City  0.7  ...         6
                        11  1.0  0.0   Manchester Utd  1.0  ...         6
                        13  0.0  3.0      Aston Villa  1.5  ...         6
...                         ...  ...              ...  ...  ...       ...
Wolverhampton Wanderers 39  0.0  6.0         Brighton  0.8  ...         5
                        40  1.0  0.0      Aston Villa  0.8  ...         5
                        41  0.0  2.0   Manchester Utd  0.3  ...         5
                        42  1.0  1.0          Everton  1.6  ...         5
                        43  0.0  5.0          Arsenal  0.5  ...         6

                            target  gf_rolling ga_rolling sh_rolling  \
team
Arsenal                 6        1    2.000000   1.333333   8.000000
                        7        0    1.666667   1.666667   5.666667
                        9        0    1.000000   1.666667   7.000000
                        11       1    0.666667   1.000000   9.666667
                        13       0    0.333333   0.666667   9.666667
...                            ...         ...        ...        ...
Wolverhampton Wanderers 39       0    1.666667   0.666667  11.666667
                        40       1    1.000000   2.666667  11.333333
                        41       0    1.000000   2.000000   8.000000
                        42       0    0.333333   2.666667   7.000000
                        43       0    0.666667   1.000000   8.000000

                           sot_rolling dist_rolling  fk_rolling  pk_rolling  \
team
Arsenal                 6     3.666667    14.633333    0.666667    0.000000
                        7     3.666667    15.366667    0.000000    0.000000
                        9     3.666667    16.566667    0.666667    0.000000
                        11    4.000000    16.566667    1.000000    0.000000
                        13    2.666667    19.333333    1.000000    0.333333
...                                ...          ...         ...         ...
Wolverhampton Wanderers 39    4.666667    18.700000    0.666667    0.333333
                        40    2.333333    18.800000    0.666667    0.333333
                        41    2.000000    17.766667    0.000000    0.333333
                        42    1.333333    15.600000    0.000000    0.000000
                        43    2.333333    15.333333    0.333333    0.000000

                            pkatt_rolling
team
Arsenal                 6        0.000000
                        7        0.000000
                        9        0.000000
                        11       0.000000
                        13       0.333333
...                                   ...
Wolverhampton Wanderers 39       0.333333
                        40       0.333333
                        41       0.333333
                        42       0.000000
                        43       0.000000

[1980 rows x 38 columns]

In [77]:
matches_rolling.index=range(matches_rolling.shape[0])

In [78]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-10-04,14:00,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,0.6,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,0.9,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,0.7,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,1.0,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,1.5,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,2023-04-29,15:00,Matchweek 34,Sat,Away,L,0.0,6.0,Brighton,0.8,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
1976,2023-05-06,15:00,Matchweek 35,Sat,Home,W,1.0,0.0,Aston Villa,0.8,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
1977,2023-05-13,15:00,Matchweek 36,Sat,Away,L,0.0,2.0,Manchester Utd,0.3,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
1978,2023-05-20,15:00,Matchweek 37,Sat,Home,D,1.0,1.0,Everton,1.6,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
1979,2023-05-28,16:30,Matchweek 38,Sun,Away,L,0.0,5.0,Arsenal,0.5,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [99]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [100]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [102]:
error

0.5382165605095541

In [82]:
combined

      actual  predicted
55         0          1
56         1          0
57         1          1
58         1          1
59         1          1
...      ...        ...
1975       0          0
1976       1          0
1977       0          0
1978       0          0
1979       0          0

[1139 rows x 2 columns]

In [103]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [104]:
combined.head()

    actual  predicted       date     team   opponent result
55       0          1 2022-01-23  Arsenal    Burnley      D
56       1          0 2022-02-10  Arsenal     Wolves      W
57       1          1 2022-02-19  Arsenal  Brentford      W
58       1          1 2022-02-24  Arsenal     Wolves      W
59       1          1 2022-03-06  Arsenal    Watford      W

In [105]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [106]:

combined["new_team"] = combined["team"].map(mapping)

In [108]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [109]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,1,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,1,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
1091,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
1092,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,1,Manchester United,Wolves,W,Manchester Utd
1093,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves,0,0,Everton,Wolves,D,Everton
1094,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal

In [110]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    145
0    104
Name: actual_x, dtype: int64